// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0ec6XCwZmjdUSl1VNpenlkhkFY3NDRrw',
    appId: '1:799215351498:web:03d419c19fb79d8bcba633',
    messagingSenderId: '799215351498',
    projectId: 'flutter-phone-auth-40f8b',
    authDomain: 'flutter-phone-auth-40f8b.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-40f8b.firebasestorage.app',
    measurementId: 'G-54F6WWBDD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-uJKR4--CS3c3JiPUvNtm_oOZERiLJ_g',
    appId: '1:799215351498:android:b4c4c0b073bac3d6cba633',
    messagingSenderId: '799215351498',
    projectId: 'flutter-phone-auth-40f8b',
    storageBucket: 'flutter-phone-auth-40f8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDTuaUDj5ATSTZahSjEwJ9e3H6WWdS3v4',
    appId: '1:799215351498:ios:6b884d6ebf2d533ecba633',
    messagingSenderId: '799215351498',
    projectId: 'flutter-phone-auth-40f8b',
    storageBucket: 'flutter-phone-auth-40f8b.firebasestorage.app',
    iosBundleId: 'com.ecommerceapp.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDTuaUDj5ATSTZahSjEwJ9e3H6WWdS3v4',
    appId: '1:799215351498:ios:6b884d6ebf2d533ecba633',
    messagingSenderId: '799215351498',
    projectId: 'flutter-phone-auth-40f8b',
    storageBucket: 'flutter-phone-auth-40f8b.firebasestorage.app',
    iosBundleId: 'com.ecommerceapp.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLqf5j9lb6q_GLCNP3Y69Yt--vJu-2rh4',
    appId: '1:799215351498:web:b9afa5ecc7d15683cba633',
    messagingSenderId: '799215351498',
    projectId: 'flutter-phone-auth-40f8b',
    authDomain: 'flutter-phone-auth-40f8b.firebaseapp.com',
    storageBucket: 'flutter-phone-auth-40f8b.firebasestorage.app',
    measurementId: 'G-ZT44YRYF2G',
  );
}
